function startTheShow() { 
  $("#create #tn").focus();
  
  getList(0);
  
  $("#create").submit(function () {
    return addTodo($(this).find("#tn").val());
  });
  
  $("#navbar #showUncompleted").click(function() {
    getList(0);
  });
  
  $("#navbar #showCompleted").click(function() {
    getList(1);
  });
  
  $("#refresh").click(function() {
    refreshList();
  });

  /* Because of an bug this doesn't work on mobile safari :-(
   * http://bugs.jquery.com/ticket/5677
  $(".entry .checkbox").live("click", function(){
    var id = $(this).parents(".entry").attr("data-id");;
      switchStatusTodo(id);
  });
  
  // this also doesnt work on mobile safari :-(
  $("body").click(function(event) {
    clog(event.target.nodeName);
    $("#debug").append(event.target.nodeName);
    if($(event.target).is(".entry .checkbox") || $(event.target).is(".entry .checkbox img")){
      var id = getID(event.target);
      switchStatusTodo(id);
    }
    if($(event.target).is(".entry .text")){
      var id = getID(event.target);
      toggleTodo(id);
    }
  });
  
  
  Workarround: livequery 
  https://gist.github.com/259656
  */
  
  $(".entry .checkbox").livequery("click", function(event){
    var id = getID(event.target);
    switchStatusTodo(id);
  });
  
  $(".entry .text").livequery("click", function(event){
    var id = getID(event.target);
    $(".entry[data-id='" + id + "']").toggleClass("expand");
  });
  
  $(".entry .edittodo").livequery("click", function(event){
    var id = getID(event.target);
    edittodo(id);
  });
  $(".entry .deletetodo").livequery("click", function(event){
    var id = getID(event.target);
    deletetodo(id);
  });
  
  $(".setpriority .low").livequery("click", function(event){
    var id = getID(event.target);
    setpriority(id, 1);
  });
  
  $(".setpriority .normal").livequery("click", function(event){
    var id = getID(event.target);
    setpriority(id, 2);
  });
  
  $(".setpriority .high").livequery("click", function(event){
    var id = getID(event.target);
    setpriority(id, 3);
  });
  
  
  
  
  
  
}

function getList(status) {  
$("#status").html("lade Liste ...");
  $.post('backend.php', {
    action: 'getList',
    status: status
  }, function (data) {
    var data = JSON.parse(data);
    clog(data);

    if (data.result === true) {
      $("#list").html("");
      $("#list").attr("data-type", data.listStatus);
      $("#status").html("");
      
      if(data.listStatus == 0) {
        $("#navbar #showCompleted").removeClass("active");
        $("#navbar #showUncompleted").addClass("active");  
      }else{
        $("#navbar #showUncompleted").removeClass("active");
        $("#navbar #showCompleted").addClass("active");  
      }
      
      
      $("#list").prepend(data.entryTpl);

    } else {
      if (data.message) {
        alert(data.message);
      }
    }
  });
}

function refreshList() {
  getList($("#list").attr("data-type"));    
}

function getID(obj) {
  return $(obj).parents(".entry").attr("data-id");
}

function addTodo(text) {
  clog('Add Todo: ' + text);
  $.post('backend.php', {
    action: 'addTodo',
    text: text
  }, function (data) {
    clog(data);
    var data = JSON.parse(data);    

    if (data.result === true) {
      // Add entry to list (tpl generated by backend.php)
      $("#list").prepend(data.entryTpl);

      // Clear Input field after saving
      $("#tn").val("");
    } else {
      if (data.message) {
        alert(data.message);
      }
    }
  });
  return false;
}

function switchStatusTodo(id) {
  clog('switch Status Todo: ' + id);

  $.post('backend.php', {
    action: 'switchStatusTodo',
    id: id
  }, function (data) {
    var data = JSON.parse(data);
    clog(data);

    if (data.result === true) {
      $(".entry[data-id='" + id + "']").toggleClass("completed");
    } else {
      if (data.message) {
        alert(data.message);
      }
    }
  });
  return false;
}

function edittodo(id) {
  clog('edit Todo: ' + id); 
}

function deletetodo(id) {
  clog('delete Todo: ' + id);
  
  var doit = confirm("Todo mit der ID "+id+" löschen?");
  if(doit) {
    $.post('backend.php', {
      action: 'deleteTodo',
      id: id
    }, function (data) {
      var data = JSON.parse(data);
      clog(data);
  
      if (data.result === true) {
        $(".entry[data-id='" + id + "']").fadeOut("slow");
      } else {
        if (data.message) {
          alert(data.message);
        }
      }
    });
  }
}

function setpriority(id, priority) {
  clog('set Priority Todo: ' + id+" "+priority);
  $.post('backend.php', {
    action: 'setPriority',
    priority: priority, 
    id: id
  }, function (data) {
    var data = JSON.parse(data);
    clog(data);

    if (data.result === true) {
      $(".entry[data-id='" + id + "']").removeClass("high");
      $(".entry[data-id='" + id + "']").removeClass("normal");
      $(".entry[data-id='" + id + "']").removeClass("low");
      if(priority == 1) {
        $(".entry[data-id='" + id + "']").addClass("low");
      }else if(priority == 2) {
        $(".entry[data-id='" + id + "']").addClass("normal");
      }else if(priority == 3) {
        $(".entry[data-id='" + id + "']").addClass("high");
      }
    } else {
      if (data.message) {
        alert(data.message);
      }
    }
  });  
}

function clog(msg) {
  console.log(msg);
}